DROP TABLE IF EXISTS REPORT_CONFIG;
CREATE TABLE REPORT_CONFIG (
report_id INT AUTO_INCREMENT  PRIMARY KEY,  
report_name VARCHAR(30) NOT NULL,  
report_type VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS COLUMN_CONFIG;
CREATE TABLE COLUMN_CONFIG (
COLUMN_ID INT AUTO_INCREMENT  PRIMARY KEY,
COLUMN_NAME VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS REPORT_COLUMN_CONFIG;
CREATE TABLE REPORT_COLUMN_CONFIG (
report_id INT,  
COLUMN_ID INT,
PRIMARY KEY (report_id,COLUMN_ID),
FOREIGN KEY (report_id) REFERENCES REPORT_CONFIG(report_id),
FOREIGN KEY (COLUMN_ID) REFERENCES COLUMN_CONFIG(COLUMN_ID)
);

DROP TABLE IF EXISTS METADATA_CONFIG;
CREATE TABLE METADATA_CONFIG (
METADATA_ID INT AUTO_INCREMENT  PRIMARY KEY,
METADATA_NAME VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS COLUMN_METADATA_CONFIG;
CREATE TABLE COLUMN_METADATA_CONFIG (
COLUMN_ID INT,
METADATA_ID INT,
METADATA_VALUE VARCHAR(30) NOT NULL,
PRIMARY KEY (COLUMN_ID, METADATA_ID),
FOREIGN KEY (COLUMN_ID) REFERENCES COLUMN_CONFIG(COLUMN_ID),
FOREIGN KEY (METADATA_ID) REFERENCES METADATA_CONFIG(METADATA_ID)
);

DROP TABLE IF EXISTS HEDGE_DATA;
CREATE TABLE HEDGE_DATA (
ID VARCHAR(5) PRIMARY KEY,
FUND_NAME VARCHAR(20) NOT NULL,
MANAGER VARCHAR(30) NOT NULL,
MANAGER_CONTACT VARCHAR(20) NOT NULL,
STRATEGY VARCHAR(30) NOT NULL,
GEO_FOCUS VARCHAR(20) NOT NULL,
FUND_INCEPTION INT NOT NULL,
MANAGER_FOUNDED INT NOT NULL
);

DROP TABLE IF EXISTS SCHEDULE_CONFIG;
CREATE TABLE SCHEDULE_CONFIG (
report_id INT PRIMARY KEY,
cron_expression VARCHAR(30)
);


